### ISSUE TITLE
AFL-operate

### ISSUE THREAD

**Issue by zheng-yan-max** [rohanpadhye/JQF#120]
Hi author, I was wondering how to use MVN to run the AFL tool. I used the Javac from your tutorial to compile the file, but I got some errors (the dependency is confirmed to be ok).Compilation has passed

These are my orders：
                   jqf/bin/jqf-afl-fuzz -i $AFL_DIR/testcases/images/png PngTest testRead
error:java.lang.ClassNotFoundException: PngTest
         at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:124)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:96)
	at edu.berkeley.cs.jqf.fuzz.repro.ReproDriver.main(ReproDriver.java:64)

**Comment by rohanpadhye** [comment]
`ClassNotFoundException: PngTest` indicates that PngTest is not on your classpath. Does playing with the`-c` option in the [tutorial](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-AFL#fuzzing-with-jqf-afl-fuzz) help? You can also make sure that you don't have environment variables that override the classpath (e.g.try `echo $CLASSPATH` in Bash).

**Comment by rohanpadhye** [comment]
Closing due to inactivity. Please reopen if needed.
