### ISSUE TITLE
Generator config error : FileNotFoundException

### ISSUE THREAD

**Issue by jubatusd** [rohanpadhye/JQF#134]
Hi,
When I tested Maven in JQF-Examples with the JQF Maven Plugin, I got a FileNotFoundException.
I use this command fuzz:
`mvn jqf:fuzz -Dclass=edu.berkeley.cs.jqf.examples.ant.ProjectBuilderTest -Dmethod=testWithGenerator -Dtime=5m`
But when I ran this method directly in IntelliJ, this didn't happen

`There was 1 failure:
1) testWithGenerator(edu.berkeley.cs.jqf.examples.maven.ModelReaderTest)
com.pholser.junit.quickcheck.internal.ReflectionException: java.io.FileNotFoundException: Dictionary file not found: dictionaries/maven-model.dict
        at com.pholser.junit.quickcheck.internal.Reflection.reflectionException(Reflection.java:255)
        at com.pholser.junit.quickcheck.internal.Reflection.invoke(Reflection.java:172)
        at com.pholser.junit.quickcheck.generator.Generator.configure(Generator.java:395)
        at com.pholser.junit.quickcheck.generator.Generator.configureStrict(Generator.java:356)
        at com.pholser.junit.quickcheck.generator.Generator.configureStrict(Generator.java:349)
        at com.pholser.junit.quickcheck.generator.Generator.configure(Generator.java:258)
        at com.pholser.junit.quickcheck.internal.generator.CompositeGenerator.configure(CompositeGenerator.java:104)
        at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.produceGenerator(FuzzStatement.java:246)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.evaluate(FuzzStatement.java:106)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:210)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:156)
        at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute(FuzzGoal.java:341)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

FAILURES!!!
Tests run: 1,  Failures: 1
`
i'm running on ubuntu20 64 bit, java 8

Thanks!

**Comment by rohanpadhye** [comment]
Thanks for the report! It looks like a classpath issue with dictionary files. For some reason, the dictionary loader was using the system class loader, which won't work with Maven.  Let me push a quick fix.

https://github.com/rohanpadhye/JQF/blob/b15d4e5f136e2b3e2083e4c1d1845e2c8ecb214e/examples/src/main/java/edu/berkeley/cs/jqf/examples/common/DictionaryBackedStringGenerator.java#L54

**Comment by rohanpadhye** [comment]
Can you try again with the latest snapshot? You'll have to clone JQF, run `mvn install`, and have your test depend on JQF version `1.8-SNAPSHOT`. If this works, I'll include it in the next release.

**Comment by jubatusd** [comment]
> Can you try again with the latest snapshot? You'll have to clone JQF, run `mvn install`, and have your test depend on JQF version `1.8-SNAPSHOT`. If this works, I'll include it in the next release.
thanks! it works now.The problem has been solved
