### ISSUE TITLE
JQF fails on JDK 16

### ISSUE THREAD

**Issue by mdindoffer** [rohanpadhye/JQF#141]
JQF 1.7 fails to run even basic Zest test from tutorials on recent JDKs.

JDK 14 and 15 seems to be working just fine, but JDK 16 fails with:
```
Semantic Fuzzing with Zest
--------------------------

Test name:            eu.dindoffer.fuzz.example.DateFormatterTest#fuzzSimple
Results directory:    /home/mao/personal/fuzz/target/fuzz-results/eu.dindoffer.fuzz.example.DateFormatterTest/fuzzSimple
Elapsed time:         2s (no time limit)
Number of executions: 92,816
Valid inputs:         92,816 (100.00%)
Cycles completed:     0
Unique failures:      0
Queue size:           0 (0 favored last cycle)
Current parent input: <seed>
Execution speed:      71,276/sec now | 38,054/sec overall
Total coverage:       0 branches (0.00% of map)
Valid coverage:       0 branches (0.00% of map)
Fuzzing stopped due to guidance exception: Too many trials without coverage; likely all assumption violations
edu.berkeley.cs.jqf.fuzz.guidance.GuidanceException: Too many trials without coverage; likely all assumption violations
	at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance.getInput(ZestGuidance.java:561)
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.evaluate(FuzzStatement.java:124)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:208)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:154)
	at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute(FuzzGoal.java:347)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

I tried to update the asm to 9.1, but that didn't solve the issue..

```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /opt/maven
Java version: 16.0.1, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-16-hotspot-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-55-generic", arch: "amd64", family: "unix"
```

**Comment by rohanpadhye** [comment]
Thanks for the report. Seems like there's no coverage instrumentation,
likely due to a small issue with class file / bytecode support. I would
have also tried updating ASM, but funny that it doesn't solve the problem.

Will look into it more this week.

**Comment by rohanpadhye** [comment]
I upgraded Java to `openjdk version "16.0.1" 2021-04-20` and JQF seems to run fine for me. I ran `mvn jqf:fuzz -Dclass=edu.berkeley.cs.jqf.examples.closure.CompilerTest -Dmethod=testWithGenerator` in the `examples` directory and things seem to work fine. Do you have a reproducible test case where the error occurs? I updated to ASM 9.1 as well as a number of other dependencies just in case but I didn't really need it to work. Can you try again with the latest in case it was something with a dependency down the line?

Alternatively, are there any Java 16 specific features that were used to compile `eu.dindoffer.fuzz.example.DateFormatterTest` in your case?

**Comment by mdindoffer** [comment]
Ah, it is working now with the latest master! Must have been some hidden dependency.

But, as you pointed out - the issue is not so much about running the fuzzer with JDK 16, rather running it on a fuzz target that was compiled with

```xml
<properties>
    <maven.compiler.source>16</maven.compiler.source>
    <maven.compiler.target>16</maven.compiler.target>
</properties>
```

If compiled against source and target **15** and lower, then JQF 1.7 works even with JDK 16.

---
You can actually reproduce it directly in JQF `examples` directory, just not on the closure compiler (I'm not sure why).
You can reproduce it on the `DateFormatterTest`. Just bump the source and target to 16, update `maven-plugin-plugin` to 3.6.1 to be able to compile it with 16 as a target, and then run in `examples`:
`mvn jqf:fuzz -Dclass=edu.berkeley.cs.jqf.examples.jdk.DateFormatterTest -Dmethod=fuzzSimple`

But as I said, the updates to dependencies did the trick. Thanks!

**Comment by rohanpadhye** [comment]
I suspect it is because there was a hidden dependency on an older version of ASM via either Jacoco or Maven compiler plugin, but bumping all the dependency versions seems to have addressed this. Thanks for the update!

**Comment by FourierX9** [comment]
Hi! I have met the same problem with the fuzzing target compiled with JDK17. And I am using maven 3.8.3. I met this problem when running the example (https://github.com/rohanpadhye/JQF/wiki/Fuzzing-with-Zest). Is there any ideas how to fix this? Thanks
