### ISSUE TITLE
Build fails with ZestGuidanceTest AssertionError

### ISSUE THREAD

**Issue by floyd-fuh** [rohanpadhye/JQF#148]
When trying to build JQF it fails in the ZestGuidanceTest. The assert `Assert.assertEquals(381936627, zest.getTotalCoverage().hashCode());` fails as the hashCode has a different value: `java.lang.AssertionError: expected:<381936627> but was:<-2072902769>`

The full error message is:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.349 s <<< FAILURE! - in edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest
[ERROR] testPatriciaTrieFuzzer(edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest)  Time elapsed: 9.301 s  <<< FAILURE!
java.lang.AssertionError: expected:<381936627> but was:<-2072902769>
	at edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.testPatriciaTrieFuzzer(ZestGuidanceTest.java:57)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ZestGuidanceTest.testPatriciaTrieFuzzer:57 expected:<381936627> but was:<-2072902769>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for jqf 1.8-SNAPSHOT:
[INFO] 
[INFO] jqf ................................................ SUCCESS [  0.019 s]
[INFO] jqf-instrument ..................................... SUCCESS [  4.316 s]
[INFO] jqf-fuzz ........................................... SUCCESS [ 10.817 s]
[INFO] jqf-maven-plugin ................................... SUCCESS [  2.563 s]
[INFO] jqf-examples ....................................... SUCCESS [  2.580 s]
[INFO] jqf-integration-tests .............................. FAILURE [ 10.301 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30.886 s
[INFO] Finished at: 2021-07-29T16:25:17Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jqf-integration-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /jqf/integration-tests/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jqf-integration-tests: There are test failures.

Please refer to /jqf/integration-tests/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /jqf/integration-tests/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
    at org.apache.maven.plugin.surefire.SurefireHelper.throwException (SurefireHelper.java:289)
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:161)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:364)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:1041)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:857)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jqf-integration-tests
[afl++ 0b532f1c9a3b] /jqf (master) # grep -nri 'ZestGuidanceTest' /jqf/
Binary file /jqf/.git/index matches
/jqf/integration-tests/src/test/java/edu/berkeley/cs/jqf/fuzz/guidance/ZestGuidanceTest.java:19:public class ZestGuidanceTest {
/jqf/integration-tests/target/surefire/surefire11121262456846020514tmp:48:tc.0=edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest
/jqf/integration-tests/target/surefire-reports/TEST-edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.xml:2:<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest" time="9.349" tests="1" errors="0" skipped="0" failures="1">
/jqf/integration-tests/target/surefire-reports/TEST-edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.xml:59:  <testcase name="testPatriciaTrieFuzzer" classname="edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest" time="9.301">
/jqf/integration-tests/target/surefire-reports/TEST-edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.xml:61:	at edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.testPatriciaTrieFuzzer(ZestGuidanceTest.java:57)
/jqf/integration-tests/target/surefire-reports/edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.txt:2:Test set: edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest
/jqf/integration-tests/target/surefire-reports/edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.txt:4:Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.349 s <<< FAILURE! - in edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest
/jqf/integration-tests/target/surefire-reports/edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.txt:5:testPatriciaTrieFuzzer(edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest)  Time elapsed: 9.301 s  <<< FAILURE!
/jqf/integration-tests/target/surefire-reports/edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.txt:7:	at edu.berkeley.cs.jqf.fuzz.guidance.ZestGuidanceTest.testPatriciaTrieFuzzer(ZestGuidanceTest.java:57)
Binary file /jqf/integration-tests/target/test-classes/edu/berkeley/cs/jqf/fuzz/guidance/ZestGuidanceTest.class matches
/jqf/integration-tests/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst:1:/jqf/integration-tests/src/test/java/edu/berkeley/cs/jqf/fuzz/guidance/ZestGuidanceTest.java
/jqf/integration-tests/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst:1:edu/berkeley/cs/jqf/fuzz/guidance/ZestGuidanceTest.class
```

Can be reproduced by trying to build the following Dockerfile. Save this content to a file called `Dockerfile` in a folder called `jqf`:

```
FROM aflplusplus/aflplusplus:latest AS jqf

ENV AFL_DIR=/AFLplusplus/

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install maven openjdk-11-jdk-headless && \
	git clone https://github.com/rohanpadhye/jqf.git /jqf && \
	cd /jqf

```

Then run:

`docker build --target jqf --tag=jqf ./jqf/`
`docker run -it --entrypoint=/bin/bash jqf`

Then when you are inside the container run:

`/jqf/setup.sh`

I had a quick look at the root cause and it seems strange to me to rely on the "total coverage" of a known-testcase and to hash it and then compare to an exact value to see if the coverage worked correctly. My guess is that coverage measuring is too non-deterministic and changing something small on the system (Java version, library providing PatriciaTrie or similar) might slightly change the coverage and therefore the test case fails.

Btw. AFL++ solves the same tests by instrumenting test code, feeding it two different inputs and then fail if the coverage is not different for both runs: https://github.com/AFLplusplus/AFLplusplus/blob/7bcd4e290111ca81d6d58d1b70696e9e9aaa5ac1/GNUmakefile#L531

**Comment by rohanpadhye** [comment]
Thanks for the report, @floyd-fuh. 

The integration-tests are new and experimental. They control for randomness in the algorithm and fix versions of dependencies, etc. so I'd love to identify the source of nondeterminism. Thanks for the Dockerfile; that will be helpful in debugging the issue.

The AFL++ approach seems interesting, but doesn't actually touch upon the kind of issues we wan't to identify---that is, small changes to performance or stats collection that accidentally disrupt the fuzzing algorithms or coverage instrumentation. Just because two inputs give the same coverage feedback, it doesn't mean that it was the _correct_ feedback. We eventually want to get to differential regression testing where we compare versions of JQF before and after a change and make sure that we get the same coverage without relying on hashes, but I haven't figured out how to do that easily yet. The goal of these tests is to ensure that the algorithm is still the same when we've made cosmetic changes or performance optimizations.

For now, I'm pushing a commit to disable these integration tests by default so that local builds won't break---but I'm still running them in CI.  Your Dockerfile may help in identifying other sources of nondeterminism. Cheers.

**Comment by floyd-fuh** [comment]
Thanks! 

Ok, great goal of trying to get the non-deterministic parts out, can be hard though

One remark: Maybe create the Docker container now (you can still debug later) to have the same version I had. Because the aflplusplus/aflplusplus:latest will be built continously I can't guarantee it will work in the future.

Thanks for disabling them, that fixed it.

**Comment by rohanpadhye** [comment]
Thanks! I downloaded it and can confirm that the test fails with the same hash code that you got (-2072902769).

In general, this issue should not depend on aflplusplus being present or its version, since the integration test is quite independent of AFL. I'll try to reproduce this from a fresh install of Ubuntu. I'm guessing the non-determinism is due to a Java version or other environment config, which will be hard to control anyway.
