### ISSUE TITLE
A Question On Coverage

### ISSUE THREAD

**Issue by FourierX9** [rohanpadhye/JQF#161]
Hi: I am using this tool to test a very small function with just if-else statement inside. And I found that the total coverage and the valid coverage is always showing 0 branches (0.00% of map). And there is a warning: Fuzzing stopped due to guidance exception: Too many trials without coverage; likely all assumption violations
edu.berkeley.cs.jqf.fuzz.guidance.GuidanceException: Too many trials without coverage; likely all assumption violations

``` code
Elapsed time:         17s (no time limit)
Number of executions: 99,116
Valid inputs:         99,116 (100.00%)
Cycles completed:     0
Unique failures:      0
Queue size:           0 (0 favored last cycle)
Current parent input: <seed>
Execution speed:      6,663/sec now | 5,718/sec overall
Total coverage:       0 branches (0.00% of map)
Valid coverage:       0 branches (0.00% of map)
Fuzzing stopped due to guidance exception: Too many trials without coverage; likely all assumption violations
edu.berkeley.cs.jqf.fuzz.guidance.GuidanceException: Too many trials without coverage; likely all assumption violations
        at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance.getInput(ZestGuidance.java:561)
        at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.evaluate(FuzzStatement.java:124)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:208)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:154)
        at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute(FuzzGoal.java:347)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.828 s
[INFO] Finished at: 2021-11-25T21:32:03-05:00
[INFO] ------------------------------------------------------------------------
```

I also tried with command: mvn jqf:repro -DlogCoverage=coverage
It has another warning that
``` code
[ERROR] Failed to execute goal edu.berkeley.cs.jqf:jqf-maven-plugin:1.7:repro (default-cli) on project testBuild: The parameters 'input', 'testClassName', 'testMethod' for goal edu.ber
keley.cs.jqf:jqf-maven-plugin:1.7:repro are missing or invalid -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```
I run this test on Java11, maven 3.8.3, jqf 1.7. I am guessing if there is some special requirement for Zest to detect the coverage?

Thanks and Happy Thanksgiving

**Comment by rohanpadhye** [comment]
Can you try the [tutorial on the wiki](https://github.com/rohanpadhye/JQF/wiki/Fuzzing-a-Compiler) or the [example target repository](https://github.com/rohanpadhye/jqf-zest-example)? Does that work or do you get the same error? I want to isolate whether it's an issue with the JQF setup or with the target program.

There was a similar issue reported in #141, which was fixed by me bumping dependencies, but that has not yet been released (last release is 1.7 in April, bump was in June). I can make a quick JQF 1.8 release if that seems to be the bottleneck. If you want to get the latest development version, you can clone the JQF repo, run `mvn install`, and depend on JQF `1.8-SNAPSHOT` in your pom.xml.

**Comment by FourierX9** [comment]
It HELPS!!! Thank you so much!!!

**Comment by FourierX9** [comment]
Hi: Sorry I came up with another question. After I use mvn jqf:repro -DlogCoverage to get the coverage report. How can I grab the coverage information from the output file? It seems to offer some information about which class and function is covered, but how can I find which line is covered? I did not find any related information in the wiki.
Thanks

**Comment by rohanpadhye** [comment]
The coverage file gives you a hint of the line number where a branch or function call was covered. For example, the line :

```
BRANCH(-1438560254,1,248) // edu/berkeley/cs/jqf/examples/js/JavaScriptCodeGenerator#generateIdentNode
```

Says that branch with unique ID `-1438560254` at line `248` of the file containing class `JavaScriptCodeGenerator` was executed, this was in method `generateIdentNode`, and the branch `1` was taken (if-else branches have only `0` or `1` as the outcome, whereas switch-case branches can have multiple outcomes).


If you want more comprehensive coverage, you can just use a tool such as JaCoCo to run the repro and get a nice HTML formatted coverage report.
