### ISSUE TITLE
NoClassDefFoundError when trying to run the CompilerTest with Zest

### ISSUE THREAD

**Issue by olli22221** [rohanpadhye/JQF#169]
Hello when running the CompilerTest Example I got the following error:

sudo ~/../../jqf/bin/jqf-zest -c .:$(../../../../../../../../../scripts/examples_classpath.sh) CompilerTest testWithString

Exception in thread "main" java.lang.NoClassDefFoundError: edu/berkeley/cs/jqf/examples/closure/CompilerTest (wrong name: CompilerTest)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:152)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:123)
	at edu.berkeley.cs.jqf.fuzz.ei.ZestDriver.main(ZestDriver.java:77)

The CompilerTest.class is in the test-classes folder!

**Comment by olli22221** [comment]
already done, thanks
