### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by floyd-fuh** [rohanpadhye/jqf#23]
I have build errors again. First trying to run `mvn package`:

```
[INFO] Reactor Summary:
[INFO] 
[INFO] jqf ............................................... SUCCESS [0.006s]
[INFO] jqf-instrument .................................... SUCCESS [6.658s]
[INFO] jqf-fuzz .......................................... SUCCESS [28.155s]
[INFO] jqf-maven-plugin .................................. FAILURE [3.624s]
[INFO] jqf-examples ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.056s
[INFO] Finished at: Tue May 08 01:26:35 ACST 2018
[INFO] Final Memory: 16M/40M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5.1:descriptor (default-descriptor) on project jqf-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: edu.berkeley.cs.jqf:jqf-maven-plugin.' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.5.1:descriptor (default-descriptor) on project jqf-maven-plugin: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: edu.berkeley.cs.jqf:jqf-maven-plugin.'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error extracting plugin descriptor: 'No mojo definitions were found for plugin: edu.berkeley.cs.jqf:jqf-maven-plugin.'
	at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:271)
	at org.apache.maven.plugin.plugin.DescriptorGeneratorMojo.execute(DescriptorGeneratorMojo.java:90)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.apache.maven.plugin.descriptor.InvalidPluginDescriptorException: No mojo definitions were found for plugin: edu.berkeley.cs.jqf:jqf-maven-plugin.
	at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:114)
	at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:259)
	... 22 more
```

Then when trying `mvn package -e -pl examples`:

```
[ERROR] Failed to execute goal on project jqf-examples: Could not resolve dependencies for project edu.berkeley.cs.jqf:jqf-examples:jar:1.0-alpha-3-SNAPSHOT: The following artifacts could not be resolved: edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT, edu.berkeley.cs.jqf:jqf-instrument:jar:1.0-alpha-3-SNAPSHOT: Could not find artifact edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT in lila-maven (https://raw.githubusercontent.com/ornicar/lila-maven/master) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project jqf-examples: Could not resolve dependencies for project edu.berkeley.cs.jqf:jqf-examples:jar:1.0-alpha-3-SNAPSHOT: The following artifacts could not be resolved: edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT, edu.berkeley.cs.jqf:jqf-instrument:jar:1.0-alpha-3-SNAPSHOT: Could not find artifact edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT in lila-maven (https://raw.githubusercontent.com/ornicar/lila-maven/master)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:210)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:117)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:258)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project edu.berkeley.cs.jqf:jqf-examples:jar:1.0-alpha-3-SNAPSHOT: The following artifacts could not be resolved: edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT, edu.berkeley.cs.jqf:jqf-instrument:jar:1.0-alpha-3-SNAPSHOT: Could not find artifact edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT in lila-maven (https://raw.githubusercontent.com/ornicar/lila-maven/master)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:189)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:185)
	... 22 more
Caused by: org.sonatype.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT, edu.berkeley.cs.jqf:jqf-instrument:jar:1.0-alpha-3-SNAPSHOT: Could not find artifact edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT in lila-maven (https://raw.githubusercontent.com/ornicar/lila-maven/master)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:375)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:183)
	... 23 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT, edu.berkeley.cs.jqf:jqf-instrument:jar:1.0-alpha-3-SNAPSHOT: Could not find artifact edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT in lila-maven (https://raw.githubusercontent.com/ornicar/lila-maven/master)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
	... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact edu.berkeley.cs.jqf:jqf-fuzz:jar:1.0-alpha-3-SNAPSHOT in lila-maven (https://raw.githubusercontent.com/ornicar/lila-maven/master)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:947)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
	at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

What am I doing wrong?

**Comment by floyd-fuh** [comment]
Might be because https://raw.githubusercontent.com/ornicar/lila-maven/master is dead? I'm not really good with all this maven things, but... is it necessary that all these dependencies are used? Can we fail safely somehow if one example can not be built?

**Comment by rohanpadhye** [comment]
Hello.

The second error you see is because you are trying to build **only** the `examples` module without the `fuzz` and `instrument` modules on which it depends, so Maven tries to search for the artifacts on the web where they don't exist.

You might want to edit your command to:
`mvn package -e -pl fuzz,instrument,examples`

The first command (simply `mvn package`) which also builds the `plugin` module should also work... Maybe you are using an older version of Maven? I've [pushed an update specifying the version of the plugin builder explicitly](https://github.com/rohanpadhye/jqf/commit/452f98cc7114c19cd912cc6ce2d2dc75bc0b015e).

To your broader question of whether you need to build all of these dependencies: ideally, no. We are in the process of releasing JQF to Maven Central as a testing plugin (similar to Junit or junit-quickcheck), so users would not even have to clone the JQF repository, let alone build it. The intended use case is simply to declare a dependency on JQF in Maven and run `mvn jqf:fuzz -Dclass=... -Dmethod=...`. That documentation has been pending for a while (issue #21), but I should write it up soon with an example repository demonstrating the use case.

**Comment by floyd-fuh** [comment]
Thanks for the patience with my Java build tool noobness :)

Perfect, `mvn package -e -pl fuzz,instrument,examples` worked fine!

It really seems that I had some mess up with my maven version again... After installer a newer maven and some more fixing of some mess with Oracle Java's /usr/lib/jvm/java-8-oracle/jre/lib/security/cacerts (I remembered I have to use Oracle Java on ARM!) it builds! Thanks
