### ISSUE TITLE
Feature request: Security Policy

### ISSUE THREAD

**Issue by floyd-fuh** [rohanpadhye/jqf#24]
Any chance we could support Java Security Policy with JQF? An example is here: https://github.com/floyd-fuh/kelinci/tree/master/examples/commons-imaging . It basically means starting Java with "java -Djava.security.manager -Djava.security.policy=java-security-policy.txt", which would then throw an exception if the Java program tries to write to a file that was not specified in the policy (whitelist). In theory it should allow finding vulnerabilities such as Server Side Request Forgery, as the code would throw an exception when the Java program tries to create a socket.

**Comment by rohanpadhye** [comment]
That's interesting. I don't actually know much about Java's security policies, but you can pass additional JVM options using the environment variable `JVM_OPTS`. So perhaps something like this should already work:

````
export JVM_OPTS="-Djava.security.manager -Djava.security.policy=java-security-policy.txt"
./bin/jqf-afl-fuzz ...
```

**Comment by floyd-fuh** [comment]
So I switched over to a x86 for some of the fuzzer, so I have better performance. They are running jqf fine, but the security manager is not working currently. I gave all the permission I could think of for now, but it simply won't run...

This is my current content of java-security-policy.txt:

```
grant {
//Runtime permissions so far not necessary, but let's just give these options so we are sure it's not a probleme in this area

    permission java.lang.RuntimePermission "getClassLoader";
    permission java.lang.RuntimePermission "setContextClassLoader";
    permission java.lang.RuntimePermission "enableContextClassLoaderOverride";
    permission java.lang.RuntimePermission "closeClassLoader";
    permission java.lang.RuntimePermission "exitVM.*";
    permission java.lang.RuntimePermission "shutdownHooks";
    permission java.lang.RuntimePermission "setFactory";
    permission java.lang.RuntimePermission "setIO";
    permission java.lang.RuntimePermission "modifyThread";
    permission java.lang.RuntimePermission "stopThread";
    permission java.lang.RuntimePermission "createClassLoader";
    permission java.lang.RuntimePermission "getenv.*";
    permission java.lang.RuntimePermission "modifyThreadGroup";
    permission java.lang.RuntimePermission "getProtectionDomain";
    permission java.lang.RuntimePermission "getFileSystemAttributes";
    permission java.lang.RuntimePermission "readFileDescriptor";
    permission java.lang.RuntimePermission "writeFileDescriptor";
    permission java.lang.RuntimePermission "loadLibrary.*";
    permission java.lang.RuntimePermission "accessClassInPackage.{package";
    permission java.lang.RuntimePermission "defineClassInPackage.{package";
    permission java.lang.RuntimePermission "queuePrintJob";
    permission java.lang.RuntimePermission "getStackTrace";
    permission java.lang.RuntimePermission "setDefaultUncaughtExceptionHandler";
    permission java.lang.RuntimePermission "preferences";
    permission java.lang.RuntimePermission "usePolicy";


//File permissions so far not necessary

    permission java.io.FilePermission "/opt/jqf/examples/target/classes/-", "read";
    permission java.io.FilePermission "/opt/jqf/examples/target/test-classes/-", "read";
    permission java.io.FilePermission "/opt/jqf/examples/target/dependency/-", "read";


//Runtime permissions necessary for JQF
    permission java.lang.RuntimePermission "accessDeclaredMembers";

//Property permissions necessary for JQF
    permission java.util.PropertyPermission "jqf.traceGenerators", "read";
    permission java.util.PropertyPermission "jqf.tracing.MATCH_CALLEE_NAMES", "read";
    permission java.util.PropertyPermission "jqf.repro.logUniqueBranches", "read";
    permission java.util.PropertyPermission "jqf.logCoverage", "read";
    permission java.util.PropertyPermission "jqf.repro.traceDir", "read";
    permission java.util.PropertyPermission "jqf.repro.logUniqueBranches", "read";

//File permissions for afl-fuzz
    permission java.io.FilePermission "/tmp/-", "read, write, delete";
    permission java.io.FilePermission "tika-corpus-only-small/-", "read";
    permission java.io.FilePermission "tika-out/-", "read, write";
    permission java.io.FilePermission "tika-out2/-", "read, write";
    permission java.io.FilePermission "tika-out3/-", "read, write";

//File permissions for Tika
    permission java.io.FilePermission "/opt/jqf/examples/target/dependency/tika-core-1.18.jar", "read";
//    permission java.io.FilePermission "/opt/jqf/examples/target/dependency/tika-parsers-1.18.jar", "read";

//Runtime permissions for Tika
    permission java.lang.RuntimePermission "getenv.TIKA_CONFIG";

//Property permissions for Tika
    permission java.util.PropertyPermission "org.apache.tika.service.error.warn", "read";
    permission java.util.PropertyPermission "tika.config", "read";
    permission java.util.PropertyPermission "tika.custom-mimetypes", "read";

//Property permissions for Tika dependencies
    permission java.util.PropertyPermission "org.apache.pdfbox.pdfparser.nonSequentialPDFParser.eofLookupRange", "read";
    permission java.util.PropertyPermission "org.apache.pdfbox.forceParsing", "read";
    permission java.util.PropertyPermission "pdfbox.fontcache", "read";
    permission java.util.PropertyPermission "file.encoding", "read";
    //WTF
    permission java.util.PropertyPermission "user.home", "read";
    //WTF
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.resourcePath", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.brokenNio", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.charset.VERSION_3", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.columnOrder", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.enforceForeignKeys", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.allowAutoNumberInsert", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.timeZone", "read";
    //WTF
    permission java.util.PropertyPermission "com.ctc.wstx.returnNullForDefaultNamespace", "read";
};
```

But when I run afl-showmap (or afl-fuzz):

```
$ JVM_OPTS="-Djava.security.manager -Djava.security.policy=java-security-policy.txt -Djava.io.tmpdir=/tmp/" ./bin/jqf-afl-showmap -m 2000 -v -c $(./scripts/examples_classpath.sh) edu.berkeley.cs.jqf.examples.tika.TikaParserTest fuzz ./tika-corpus-only-small/206.tiff 
afl-showmap 2.52b by <lcamtuf@google.com>
[*] Executing '/opt/jqf/bin/jqf-afl-target'...

-- Program output begins --
-- Program output ends --

[-] PROGRAM ABORT : No instrumentation detected
         Location : main(), afl-showmap.c:773
```

Usually if a permission is missing, it will throw an exception. So if JQF catches all exceptions somewhere, that might be the issue... any idea what the problem could be?

**Comment by floyd-fuh** [comment]
Here's a policy file that seems to be working for me for JQF+Tika:

```
grant {
//Runtime and Reflect permissions necessary for JQF
    permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
    permission java.lang.RuntimePermission "accessDeclaredMembers";
    permission java.lang.RuntimePermission "getenv.ru.vyarus.java.generics.resolver.context.GenericsInfoFactory.cache";

//Property permissions necessary for JQF
    permission java.util.PropertyPermission "ru.vyarus.java.generics.resolver.context.GenericsInfoFactory.cache", "read";
    permission java.util.PropertyPermission "jqf.afl.TIMEOUT", "read";
    permission java.util.PropertyPermission "jqf.traceGenerators", "read";
    permission java.util.PropertyPermission "jqf.tracing.MATCH_CALLEE_NAMES", "read";
    permission java.util.PropertyPermission "jqf.repro.logUniqueBranches", "read";
    permission java.util.PropertyPermission "jqf.logCoverage", "read";
    permission java.util.PropertyPermission "jqf.repro.traceDir", "read";
    permission java.util.PropertyPermission "jqf.repro.logUniqueBranches", "read";

//File permissions for afl-fuzz
    permission java.io.FilePermission "/tmp/-", "read, write, delete";
    permission java.io.FilePermission "tika-corpus-only-small/-", "read";
    permission java.io.FilePermission "tika-out/-", "read, write";
    permission java.io.FilePermission "tika-out2/-", "read, write";
    permission java.io.FilePermission "tika-out3/-", "read, write";

//File permissions for Tika
    permission java.io.FilePermission "/opt/jqf/examples/target/dependency/tika-core-1.18.jar", "read";
    permission java.io.FilePermission "/opt/jqf/examples/target/dependency/tika-parsers-1.18.jar", "read";

//Runtime permissions for Tika
    permission java.lang.RuntimePermission "getenv.TIKA_CONFIG";

//Property permissions for Tika
    permission java.util.PropertyPermission "org.apache.tika.service.error.warn", "read";
    permission java.util.PropertyPermission "tika.config", "read";
    permission java.util.PropertyPermission "tika.custom-mimetypes", "read";

//Property permissions for Tika dependencies
    permission java.util.PropertyPermission "org.apache.pdfbox.pdfparser.nonSequentialPDFParser.eofLookupRange", "read";
    permission java.util.PropertyPermission "org.apache.pdfbox.forceParsing", "read";
    permission java.util.PropertyPermission "pdfbox.fontcache", "read";
    permission java.util.PropertyPermission "file.encoding", "read";
    //WTF
    permission java.util.PropertyPermission "user.home", "read";
    //WTF
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.resourcePath", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.brokenNio", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.charset.VERSION_3", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.columnOrder", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.enforceForeignKeys", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.allowAutoNumberInsert", "read";
    permission java.util.PropertyPermission "com.healthmarketscience.jackcess.timeZone", "read";
    //WTF
    permission java.util.PropertyPermission "com.ctc.wstx.returnNullForDefaultNamespace", "read";
};
```

Keep in mind that this is a trial-and-error whitelist policy created for the corpus I have. Parts of the code I don't reach with my corpus might need more permissions.

Performance seems to be fine too, on the new x86 machine I get around 10 execs/sec without the policy and with the policy.

However, it seems to me that with the policy, less paths are found (maybe it's just coincidence). Is there a good explanation for that?

And is it normal that jqf.log has exceptions in it such as the followin?

```
[JANALA] Error instrumenting class org/apache/tika/config/ServiceLoader
java.lang.RuntimeException: Cannot handle jumps before super/this
        at janala.instrument.SnoopInstructionMethodAdapter.visitJumpInsn(SnoopInstructionMethodAdapter.java:846)
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1481)
[...]
```

```
[JANALA] Error instrumenting class javax/xml/parsers/FactoryFinder
java.lang.RuntimeException: java.io.IOException: Cannot create ClassReader for type java/util/Properties
        at janala.instrument.SafeClassWriter.getCommonSuperClass(SafeClassWriter.java:100)
        at org.objectweb.asm.ClassWriter.getMergedType(ClassWriter.java:1729)
        at org.objectweb.asm.Frame.merge(Frame.java:1530)
        at org.objectweb.asm.Frame.merge(Frame.java:1429)
[...]
```

**Comment by rohanpadhye** [comment]
The exceptions in the log file that you see are due to the inability of JQF to instrument some classes, due to code patterns such as those described in #22. Unfortunately, this means that those classes will not be instrumented (and branches in their methods will not be recorded). However, it is fine in that JQF will just skip those classes and instrument everything else that it can.

As to why you are seeing fewer paths with the use of the policy, I cannot say for sure. As I said, I don't have much experience with security policies in Java, but perhaps I can try reproducing your experiment to see if I can find any anomalies.
