### ISSUE TITLE
"Pilot run failed!!!" because "Could not instantiate a Junit runner for method class"

### ISSUE THREAD

**Issue by pachulo** [rohanpadhye/jqf#31]
I'm getting this error when trying to use `jqf-afl-fuzz`:

```
[me@computer validation-commons]$ ~/tools/jqf/bin/jqf-afl-fuzz -c ./target/test-classes/ com.my-company.products.AA.validation.commons.BB.DecoderFuzzerTest fuzzWhenDecoding                                                                                      
Performing pilot run....  ERROR: Pilot run failed!!!
java.lang.IllegalArgumentException: Could not instantiate a Junit runner for method class com.my-company.products.AA.validation.commons.BB.DecoderFuzzerTest#fuzzWhenDecoding.
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:172)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:126)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:96)
        at edu.berkeley.cs.jqf.fuzz.repro.ReproDriver.main(ReproDriver.java:64)
```
The method works fine using the goal `jqf:fuzz` of the maven plugin.

**Comment by rohanpadhye** [comment]
Hello!

The error above usually occurs when JUnit cannot instantiate the test method. Are you sure that the method name is correct, that the method has been declared as `public void`, and that it is annotated with `@Fuzz`?
