### ISSUE TITLE
 An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by Ahmedfir** [rohanpadhye/jqf#41]
I have noticed this warning trace in my fuzzing log. It said "please report it", so that's what I am doing. I have no idea how to reproduce it...

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by edu.berkeley.cs.jqf.instrument.tracing.SingleSnoop (.../.m2/repository/edu/berkeley/cs/jqf/jqf-instrument/1.1/jqf-instrument-1.1.jar) to field java.lang.Thread.target
WARNING: Please consider reporting this to the maintainers of edu.berkeley.cs.jqf.instrument.tracing.SingleSnoop
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "myThread" java.lang.IllegalStateException: class edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance only supports single-threaded apps at the moment
	at edu.berkeley.cs.jqf.fuzz.ei.ZestGuidance.generateCallBack(ZestGuidance.java:880)
	at edu.berkeley.cs.jqf.instrument.tracing.ThreadTracer.spawn(ThreadTracer.java:107)
	at edu.berkeley.cs.jqf.instrument.tracing.TraceLogger.lambda$new$0(TraceLogger.java:39)
	at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at edu.berkeley.cs.jqf.instrument.tracing.TraceLogger.log(TraceLogger.java:43)
	at janala.logger.AbstractLogger.METHOD_BEGIN(AbstractLogger.java:698)
	at edu.berkeley.cs.jqf.instrument.tracing.SingleSnoop.METHOD_BEGIN(SingleSnoop.java:999)
	at randoop.util.ProgressDisplay.run(ProgressDisplay.java)

**Comment by rohanpadhye** [comment]
Thanks for the report! You can safely ignore the illegal reflective access for now. We use it to get a handle on a Runnable of an arbitrary Thread. It's hacky, but allows us to instrument multi-threaded programs while fuzzing.

That said, the exception stack trace you see below is `Exception in thread "myThread" java.lang.IllegalStateException: [...]`. That is because the implementation of Zest currently supports only single-threaded apps. If the program you are trying to fuzz is multi-threaded, consider using [JQF+AFL](https://github.com/rohanpadhye/jqf/wiki/Fuzzing-with-AFL) instead.  In general, fuzzing multi-threaded apps is a bit tricky because execution paths / code coverage may not be deterministic.

If your test program is only spawning extra threads that you are okay with ignoring during fuzzing, then you can continue to run Zest as-is. Simply ignore the IllegalStateException(s) raised from the extra threads. Zest will only get code coverage feedback from the main thread.

**Comment by Ahmedfir** [comment]
Indeed, I am using a multithreaded generator. Therefore, I am noticing odd behaviours all over the generator executions and the fuzzing as well.

Another issue, may be you could help me with:


Caused by: java.lang.IllegalArgumentException: bad range, 0 > -1
	at com.pholser.junit.quickcheck.internal.Ranges.checkRange(Ranges.java:62)
	at com.pholser.junit.quickcheck.internal.Ranges.choose(Ranges.java:87)
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FastSourceOfRandomness.fastChooseIntInRange(FastSourceOfRandomness.java:123)
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FastSourceOfRandomness.nextInt(FastSourceOfRandomness.java:98)

**Comment by Ahmedfir** [comment]
Anyway, I am going to create another simple generator using only one thread and check if this issue is still persisting or not. I will keep you updated (and share with you code, if the issue persists). Thank you again for your help !!!

**Comment by Ahmedfir** [comment]
I am closing this issue and opening a new one related to the source of randomness: the bad range one.
