### ISSUE TITLE
Fuzzing stopped due to guidance exception: java.lang.IllegalArgumentException: bad range, 0 > -1

### ISSUE THREAD

**Issue by Ahmedfir** [rohanpadhye/jqf#44]
I have created a very small generator with a very simple test to test the library.
I have tried to follow the existing examples.
I am getting an issue after some fuzzing iterations.
Could you please help me knowing if this is an internal known issue? Or am I doing any mistake in my generator and test implementation?
Please find below the source code of my Generator and my test, followed by the exception stacktrace.  

Many thanks again for your help and support!!! 

**Generator**

`
public class SeedsGenerator extends ArrayListGenerator {

    public SeedsGenerator() {
        super();
    }

    @Override
    public ArrayList<Object> generate(SourceOfRandomness random, GenerationStatus status) {
        return getObjectSeeds(random,status);
    }

    private static final int SHORT_MEAN_NUMBER = 5;
    private static final int INT_MEAN_NUMBER = 5;
    private static final int LONG_MEAN_NUMBER = 5;
    private static final int DOUBLE_MEAN_NUMBER = 5;
    private static final int FLOAT_MEAN_NUMBER = 5;
    private static final int CHAR_MEAN_NUMBER = 4;
    private static final int BOOLEAN_MEAN_NUMBER = 2;
    private static final int STRING_MEAN_NUMBER = 2;

    private static Generator<String> stringGenerator = new StringGenerator();
    private static GeometricDistribution geometricDistribution =
            new GeometricDistribution();

    private static String makeString(SourceOfRandomness random, GenerationStatus status) {
        return stringGenerator.generate(random, status);
    }

    private SeedsGenerator() {
        throw new IllegalAccessError("no instance creation. static access only.");
    }

    public static ArrayList<Object> getObjectSeeds(SourceOfRandomness randomness, GenerationStatus generationStatus) {
        ArrayList<Object> seeds;

        seeds = new ArrayList<>();
        int numShorts = Math.max(1, geometricDistribution.sampleWithMean(SeedsGenerator.SHORT_MEAN_NUMBER, randomness));
        int numInts = Math.max(1, geometricDistribution.sampleWithMean(SeedsGenerator.INT_MEAN_NUMBER, randomness));
        int numLongs = Math.max(1, geometricDistribution.sampleWithMean(SeedsGenerator.LONG_MEAN_NUMBER, randomness));
        int numStrings = Math.max(1, geometricDistribution.sampleWithMean(SeedsGenerator.STRING_MEAN_NUMBER, randomness));
        int numChars = Math.max(1, geometricDistribution.sampleWithMean(SeedsGenerator.CHAR_MEAN_NUMBER, randomness));
        int numDoubles = Math.max(1, geometricDistribution.sampleWithMean(SeedsGenerator.DOUBLE_MEAN_NUMBER, randomness));
        int numFloats = Math.max(1, geometricDistribution.sampleWithMean(SeedsGenerator.FLOAT_MEAN_NUMBER, randomness));
        int numBooleans = Math.max(1, geometricDistribution.sampleWithMean(SeedsGenerator.BOOLEAN_MEAN_NUMBER, randomness));

// in some cases the same object will be generated twice. we don't care about this repeated seed and leave zest and do the magic.

        for (int i = 0; i < numShorts; i++) {
            seeds.add((short) randomness.nextInt());
        }
        for (int i = 0; i < numInts; i++) {
            seeds.add(randomness.nextInt());
        }
        for (int i = 0; i < numLongs; i++) {
            seeds.add(randomness.nextLong());
        }
        for (int i = 0; i < numStrings; i++) {
            makeString(randomness, generationStatus);
        }
        for (int i = 0; i < numChars; i++) {
            String str = makeString(randomness, generationStatus);
            int charPos = randomness.nextInt(0, str.length() - 1);
            seeds.add(str.charAt(charPos));
        }
        for (int i = 0; i < numDoubles; i++) {
            seeds.add(randomness.nextDouble());
        }
        for (int i = 0; i < numFloats; i++) {
            seeds.add(randomness.nextFloat());
        }
        for (int i = 0; i < numBooleans; i++) {
            seeds.add(randomness.nextBoolean());
        }

        return seeds;
    }

}
`

**test**

`import com.pholser.junit.quickcheck.From;
import edu.berkeley.cs.jqf.fuzz.Fuzz;
import edu.berkeley.cs.jqf.fuzz.JQF;
import org.junit.runner.RunWith;

import java.util.List;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

@RunWith(JQF.class)
public class SeedsGeneratorTest {

    private static int fuzzIteration = 0;

    @Fuzz
    public void testSeedsGeneration(@From(SeedsGenerator.class) List<Object> seeds) {
        ++fuzzIteration;
        System.out.println("fuzzIteration = " + fuzzIteration);
        assertTrue("seeds should be not null", seeds != null);
        assertFalse("seeds list should not be empty", seeds.isEmpty());
        assertTrue("seeds list should be more than 4", seeds.size() > 4); // I guiding the generator to generate Lists with more than 4 items.
    }
}
`

**exception stack trace**

`
Fuzzing stopped due to guidance exception: java.lang.IllegalArgumentException: bad range, 0 > -1
edu.berkeley.cs.jqf.fuzz.guidance.GuidanceException: java.lang.IllegalArgumentException: bad range, 0 > -1
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.evaluate(FuzzStatement.java:159)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:184)
	at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:126)
	at edu.berkeley.cs.jqf.plugin.FuzzGoal.execute(FuzzGoal.java:207)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: java.lang.IllegalArgumentException: bad range, 0 > -1
	at com.pholser.junit.quickcheck.internal.Ranges.checkRange(Ranges.java:62)
	at com.pholser.junit.quickcheck.internal.Ranges.choose(Ranges.java:87)
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FastSourceOfRandomness.fastChooseIntInRange(FastSourceOfRandomness.java:123)
	at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FastSourceOfRandomness.nextInt(FastSourceOfRandomness.java:98)
	`

**Comment by rohanpadhye** [comment]
Hi @Ahmedfir .

I ran your example and was able to reproduce the exception. It looks like a bug in your generator. The exception stack trace shows that the `IllegalArgumentException` arises from this line:

```int charPos = randomness.nextInt(0, str.length() - 1);```

I'm assuming that you are generating an empty string via `makeString()`, and therefore the above call is `nextInt(0, -1)`, which is an invalid range.

Closing because this does not look like a bug in JQF.

**Comment by Ahmedfir** [comment]
Hi Rohan,
Many many thanks for the effort and the detailed answer! That’s very kind! I really appreciate it! 
I will have a look in my generator and avoid random empty strings. I am very sorry to make you finding bugs in my code... Thanks again for your help!
Cheers 
Ahmed 

Envoyé de mon iPhone
