### ISSUE TITLE
Suggestion/Discussion: Packaging

### ISSUE THREAD

**Issue by yevgenypats** [rohanpadhye/jqf#52]
I think a common use-case for fuzzers is to run them on remote machines and not just locally from IDE like unit-tests. The current solution is to checkout out the entire code on the remote machine or bring the main jar + test class + jqf jar to a remote machine and use the ZestDriver directly or via the `./jqf-zest` which involves quite a lot of steps.

I thought about adding something like `mvn jqf:package -Dclass=classname -Dmethod=method` that would output a jar that can just be run via `java -jar fuzzer.jar`

what do you think? how feasible this is and what obstacles you think I'll go into if I would add such capability.

**Comment by yevgenypats** [comment]
@rohanpadhye because the classname and the method name are passed I thought calling somehow `java cmf` or some other equivalent commend/plugin as well as somehow baking the classname and the method to the ZestDriver this will help preventing passing the same parameters twice. once in the `mvn jqf:package` and once in `jara -jar fuzzer.jar`.

one problem that I see is that probably it won't be possible to bake the instrumentation library and it will still involve `java -Xbootclasspath/a:"$INST_CLASSPATH" fuzzer.ar` which is better but not perfect imo.

**Comment by rohanpadhye** [comment]
If I understand you correctly, you would like a single JAR whose main method just starts fuzzing, similar to how libFuzzer works. Adding a new goal on the Maven plugin such as `jqf:package` indeed sounds like the best idea. If we somehow piggy-back on Maven's fat-jar assembly, we will have packaged a new JAR which has the app + all its dependencies + jqf-fuzz (which contains the drivers). The arguments to `mvn jqf:package` could be used to create a `.properties` file that is bundled in the JAR (and included in the classpath); these properties could be used to configure the fuzz driver (e.g. EXIT_ON_CRASH) as well as provide the target class and method (e.g. ZestDriver could look up system properties if command-line args are not given). 

The main challenge that I see is of course instrumenting from the boot class path. I don't think you can specify this in the MANIFEST.MF file or anywhere else in the JAR. However, we only need the instrumentation JAR to be in the bootclasspath if we want to instrument JDK classes, or anything else that JQF/JUnit/Maven depends on. If we assume that the application classes are all distinct and we only want to instrument user-provided app classes, then we can use the classloader trick that is currently used by the `jqf:fuzz` Maven goal. See [InstrumentingClassLoader](https://github.com/rohanpadhye/jqf/blob/master/instrument/src/main/java/edu/berkeley/cs/jqf/instrument/InstrumentingClassLoader.java). For this trick, the main driver (e.g. ZestDriver) will need to pass this class loader to the GuidedFuzzing.run() method, just like it is done in the Maven fuzz goal: https://github.com/rohanpadhye/jqf/blob/b52a361b4defc359e40c9251f8319aae2c61df11/maven-plugin/src/main/java/edu/berkeley/cs/jqf/plugin/FuzzGoal.java#L220-L222 https://github.com/rohanpadhye/jqf/blob/b52a361b4defc359e40c9251f8319aae2c61df11/maven-plugin/src/main/java/edu/berkeley/cs/jqf/plugin/FuzzGoal.java#L237

**Comment by rohanpadhye** [comment]
To clarify, if using the InstrumentingClassLoader trick, then the `jqf-instrument` artifact from Maven simply needs to be added as a normal dependency; it does not need to be in the bootclasspath.

**Comment by yevgenypats** [comment]
That makes a lot of sense. I'll try to pull this off and open a PR. Thanks for the detailed instructions!

**Comment by yevgenypats** [comment]
I found this library which assembles jar files together with test files:

https://github.com/apache/maven-assembly-plugin
http://maven.apache.org/plugins/maven-assembly-plugin/

This was found according to this stackoverflow post:
https://stackoverflow.com/questions/36047637/how-can-i-include-test-classes-into-maven-jar-and-execute-them

Do you think this would be the right solution calling this library directly from jqf maven plugin?

**Comment by yevgenypats** [comment]
@rohanpadhye so after some more research I got to understanding that as a first step it might be better not to implement this package logic as part of JQF as there are some corner cases that I'm not sure it's a good idea that it will be part of JQF.

So as a first step I just want to prepare instruction how to use the maven assembly plugin externally and then to run the JQF fuzzer or upload to Fuzzit.

I'm preparing an example here: https://github.com/fuzzitdev/example-java

but I still get some weird error that maybe you know what I'm missing. 

```bash
1) fuzz(dev.fuzzit.examplejava.ParseComplexFuzz)
java.lang.IllegalArgumentException: Cannot find generator for dev.fuzzit.examplejava.ParseComplexFuzz.fuzz:arg0 of type java.lang.String
        at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.matchingGenerators(GeneratorRepository.java:256)
        at com.pholser.junit.quickcheck.internal.generator.GeneratorRepository.generatorFor(GeneratorRepository.java:237)
        at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.produceGenerator(FuzzStatement.java:240)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at edu.berkeley.cs.jqf.fuzz.junit.quickcheck.FuzzStatement.evaluate(FuzzStatement.java:106)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:184)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:126)
        at edu.berkeley.cs.jqf.fuzz.junit.GuidedFuzzing.run(GuidedFuzzing.java:96)
        at edu.berkeley.cs.jqf.fuzz.ei.ZestDriver.main(ZestDriver.java:69)

FAILURES!!!
Tests run: 1,  Failures: 1
```

here are the steps to reproduce.

```bash
git clone https://github.com/fuzzitdev/example-java
cd example-java
 docker run -v `pwd`:/app -it maven:3.6.1-jdk-12 /bin/bash
cd /app
mvn package
java -jar /app/target/example-java-1.0-SNAPSHOT-fat-tests.jar dev.fuzzit.examplejava.ParseComplexFuzz fuzz
```

**Comment by yevgenypats** [comment]
I was able to boil down the issue and reproduce it only  with junit-quickcheck without JQF. here is the issue for reference https://github.com/pholser/junit-quickcheck/issues/232

**Comment by rohanpadhye** [comment]
Interesting. Thanks for following up with them. 

On the packaging front, I do think that `maven-assembly-plugin` is the right approach: I've used it before for other projects and it works quite well. My usage was to assemble an application far JAR though, so it only required adding the appropriate config in my pom.xml file. I haven't tried programmatically running the assembly plugin from a custom Maven plugin goal, but hopefully that is just as easy to do.

**Comment by yevgenypats** [comment]
Cool. The problem now that it doesn't even work with the pom.xml I'm
waiting for their response as well as try to debug it myself but I'm a bit
stuck. For some reasons the default generators doesn't load...

**Comment by yevgenypats** [comment]
Closing this issue as it was solved with https://github.com/rohanpadhye/jqf/pull/56
